### ISSUE TITLE
File path issues on linux

### ISSUE THREAD

**Issue by NotStirred** [luvyana/Piana#16]
Using release [1.0.11](https://github.com/luvyana/Piana/releases/tag/1.0.11)

When enabling the addon, it fails with this stacktrace:

```
Traceback (most recent call last):
  File "/home/USER/blender/blender-3.1.2-linux-x64/3.1/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/home/USER/.config/blender/3.1/scripts/addons/Piana/__init__.py", line 31, in <module>
    auto_load.init()
  File "/home/USER/.config/blender/3.1/scripts/addons/Piana/auto_load.py", line 25, in init
    modules = get_all_submodules(Path(__file__).parent)
  File "/home/USER/.config/blender/3.1/scripts/addons/Piana/auto_load.py", line 53, in get_all_submodules
    return list(iter_submodules(directory, directory.name))
  File "/home/USER/.config/blender/3.1/scripts/addons/Piana/auto_load.py", line 57, in iter_submodules
    yield importlib.import_module("." + name, package_name)
  File "/home/USER/blender/blender-3.1.2-linux-x64/3.1/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/USER/.config/blender/3.1/scripts/addons/Piana/operators.py", line 4, in <module>
    from .mods.liana_main import *
  File "/home/USER/.config/blender/3.1/scripts/addons/Piana/mods/liana_main.py", line 12, in <module>
    from .liana.helpers import *
  File "/home/USER/.config/blender/3.1/scripts/addons/Piana/mods/liana/helpers.py", line 12, in <module>
    FILEBROWSER_PATH = os.path.join(os.getenv('WINDIR'), 'explorer.exe')
  File "/home/USER/blender/blender-3.1.2-linux-x64/3.1/python/lib/python3.10/posixpath.py", line 76, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by GetzMa** [comment]
Hi, even with fixed path I don’t think you will beable to import anything, cause of the .exe it uses. So there would have to be changed even more. You should consider getting a Windows installation.

**Comment by NotStirred** [comment]
if it's a .net executable it should run fine with mono or .net core

**Comment by GetzMa** [comment]
i only know wine and got told it doesn´t work that well to run multiple applications that have to work together

**Comment by NotStirred** [comment]
.net core is published by microsoft to run .net binaries, it might have a chance of working

I may look into it tomorrow if I remember

**Comment by Devostated** [comment]
You can get valorant on linux? thought that anticheat would go ham lol
I can look into Linux path stuff tomorrow (even tho i think it's kinda waste of time tbh), but no chance that I could do any umodel modifications

**Comment by floxay** [comment]
> `FILEBROWSER_PATH = os.path.join(os.getenv('WINDIR'), 'explorer.exe')`

I believe the env var WINDIR and explorer.exe says it all.
