### ISSUE TITLE
'AttributeError' when trying to import any map

### ISSUE THREAD

**Issue by HenokW** [luvyana/Piana#26]
```
Python: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Piana\operators.py", line 21, in execute
    import_map(addon_prefs)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Piana\mods\liana_main.py", line 1569, in import_map
    import_umap(settings=settings, umap_data=umap_data, umap_name=umap_name)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Piana\mods\liana_main.py", line 1303, in import_umap
    set_materials(settings=settings, byo=imported_object, map_object=map_object)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Piana\mods\liana_main.py", line 272, in set_materials
    obj_data = byo.data
AttributeError: 'NoneType' object has no attribute 'data'

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Piana\operators.py", line 21, in execute
    import_map(addon_prefs)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Piana\mods\liana_main.py", line 1569, in import_map
    import_umap(settings=settings, umap_data=umap_data, umap_name=umap_name)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Piana\mods\liana_main.py", line 1303, in import_umap
    set_materials(settings=settings, byo=imported_object, map_object=map_object)
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\Piana\mods\liana_main.py", line 272, in set_materials
    obj_data = byo.data
AttributeError: 'NoneType' object has no attribute 'data'

location: <unknown location>:-1

**Comment by luvyana** [comment]
Closing as there is not enough info, also fixed in version 2.
